environment:
  PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Git\cmd;C:\Program Files\7-Zip
  DEPLOY_PROVIDER: bintray
  BINTRAY_USER: jeroen
  BINTRAY_TARGET: rtools
  BINTRAY_REPOSITORY: installer  
  matrix:
    - MSYS_VERSION: msys32
      RTOOLS_NAME: rtools32
      RTOOLS_ARCH: i686
    - MSYS_VERSION: msys64
      RTOOLS_NAME: rtools64
      RTOOLS_ARCH: x86_64

  PfxUri:
    secure: z+vP1iY4odY07BV7v+yfuA2MBKQFFLGokZoefPhz22evsMT/KnwtB4NgcYNLJheI
  CertPassword:
    secure: nwSwtaLCl6Xo5sfqKLvO30aFFGCgjGJ2GKTqS33zkJg=
  SignTool: C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe
  KeyFile: C:\jeroen.pfx

clone_folder: C:\%MSYS_VERSION%\home\installer

matrix:
  fast_finish: true

install:
    - ps: Import-Module .\scripts.ps1
    - ps: bootstrap

build_script:
  - C:\%MSYS_VERSION%\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/make-rtools-chroot.sh"
  - ps: InnoBuild
  - 7z a rtools40-%RTOOLS_ARCH%.7z .\build\rtools40\

after_build:
  - ps: Start-FileDownload $env:PfxUri -FileName $env:KeyFile
  - ps: SignFiles "Output\*.exe"
  - ps: Remove-Item –path $env:KeyFile

test: off

artifacts:
  - path: rtools*.7z
  - path: Output\*.exe

deploy:
  - provider: BinTray
    username: $(BINTRAY_USER)
    subject: $(BINTRAY_TARGET)
    repo: $(BINTRAY_REPOSITORY)
    package: $(RTOOLS_NAME)
    version: latest
    publish: true
    override: true
    api_key:
      secure: rKoNWcAgUrOM7QLX4cEvA1iKoY2DR4ps/1PRveq7rJknjQjcpKx8xGs42CJPhDwJ
    on:
      branch: master
